// champions.js - Data and Reporting for Bar 8 Champions League
const ChampionsLeague = {
    matches: [
        { p1: "Alastair 'kiwi' Key", p1Start: 2, p2: "Freddie Russell", p2Start: 0 },
        { p1: "Anthony Illingworth", p1Start: -2, p2: "Freddie Russell", p2Start: 3 },
        { p1: "Freddie Russell", p1Start: 0, p2: "Rumeen Farsad", p2Start: 0 },
        { p1: "Freddie Russell", p1Start: 0, p2: "GUY SMITH", p2Start: 1 },
        { p1: "Freddie Russell", p1Start: 0, p2: "DARREN PALMER", p2Start: 1 },
        { p1: "JAMIE WHITE", p1Start: -2, p2: "Frederick Russell", p2Start: 3 },
        { p1: "Freddie Russell", p1Start: 0, p2: "Jaymesh Patel", p2Start: 2 },
        { p1: "Freddie Russell", p1Start: 0, p2: "STEVE WEBB", p2Start: 6 }
    ],

    populateDropdown: function(dropdownId) {
        const dropdown = document.getElementById(dropdownId);
        if (!dropdown) return;
        dropdown.innerHTML = '<option value="">-- Choose Match --</option>';
        this.matches.forEach((match, index) => {
            const option = document.createElement('option');
            option.value = index;
            option.textContent = `${match.p1} [${match.p1Start}] vs ${match.p2} [${match.p2Start}]`;
            dropdown.appendChild(option);
        });
    },

    // YOUR NEW REPORT FUNCTION INTEGRATED HERE
    generateReport: function() {
        const now = new Date();
        const datePart = now.toLocaleDateString('en-GB');
        const timePart = now.toLocaleTimeString('en-GB', { hour12: false });
        const dateStr = `${datePart}, ${timePart}`;
        const durationText = getDuration(); // Assumes getDuration exists in script.js
        
        let report = `╔═════════════════════════════════════════════════════╗\n`;
        report +=    `║                 Bar 8 Champions League              ║\n`;
        report +=    `╚═════════════════════════════════════════════════════╝\n\n`;
        
        const raceCount = Math.max(1, gameState.p1Matches + gameState.p2Matches);
        
        report += `DATE:      ${dateStr}\n`;
        report += `MATCH ID:  ${gameState.matchID || 'SESSION-ACTIVE'}\n`; 
        report += `TYPE:      RACE TO ${gameState.raceTo} * ${raceCount}\n`;
        report += `STATUS:    FINISHED ✅\n`;
        report += `DURATION:  ${durationText}\n`;
        report += `------------------------------------------------------\n`;
        report += `SCORE:     ${gameState.p1Name} (${gameState.p1Matches}) - ${gameState.p2Name} (${gameState.p2Matches})\n`;
        report += `------------------------------------------------------\n`;

        let totalP1F = 0, totalP1A = 0, totalP2F = 0, totalP2A = 0;
        matchHistory.forEach(f => {
            if (f.winner === gameState.p1Name) { totalP1F++; totalP2A++; }
            else { totalP2F++; totalP1A++; }
        });

        report += `PLAYER STATISTICS:\n`;
        report += `${gameState.p1Name.padEnd(15)} | DISHES: ${gameState.p1Dishes} | REV: ${gameState.p1RevDishes}\n`;
        report += `${gameState.p1Name.padEnd(15)} | FRAME-F: ${totalP1F} | FRAME-A: ${totalP1A}\n`;
        report += `${gameState.p2Name.padEnd(15)} | DISHES: ${gameState.p2Dishes} | REV: ${gameState.p2RevDishes}\n`;
        report += `${gameState.p2Name.padEnd(15)} | FRAME-F: ${totalP2F} | FRAME-A: ${totalP2A}\n`;
        report += `------------------------------------------------------\n\n`;

        report += `MATCH LOG:\n`;
        
        let raceP1 = 0, raceP2 = 0;
        let cumP1 = 0, cumP2 = 0;

        matchHistory.forEach((item, index) => {
            const frameStr = `FRAME ${item.frame}`.padEnd(10);
            const winnerStr = `WINNER: ${item.winner}`.padEnd(20);
            const typeStr = item.type.replace('golden-break', 'GOLDEN-BREAK').replace('break-dish', 'BREAK-DISH').replace('reverse-dish', 'REVERSE-DISH').toUpperCase();
            
            report += `[✔] ${frameStr} | ${winnerStr} | ${typeStr}\n`;
            
            if (item.winner === gameState.p1Name) { raceP1++; cumP1++; }
            else { raceP2++; cumP2++; }

            let isEndOfRace = false;
            if (gameState.raceTo === 12) {
                 if (raceP1 === 9 || raceP2 === 9 || (raceP1 + raceP2 === 12)) isEndOfRace = true;
            } else {
                 if (raceP1 >= gameState.raceTo || raceP2 >= gameState.raceTo) isEndOfRace = true;
            }

            if (isEndOfRace) {
                report += `\n${gameState.p1Name.padEnd(15)} | FRAME-F: ${cumP1} | FRAME-A: ${cumP2}\n`;
                report += `${gameState.p2Name.padEnd(15)} | FRAME-F: ${cumP2} | FRAME-A: ${cumP1}\n\n`;
                raceP1 = 0; raceP2 = 0; 
            }
        });

        report += `\n______________________________________________________\n`;
        report += `            GENERATED BY Freddie Russell          `;
        
        return report;
    }
};

// Division 1 Singles League (Red)
const SinglesLeague = {
    matches: [
        { p1: "Freddie Russell", p1Start: 0, p2: "JOHN CROFT", p2Start: 0 },
        { p1: "MICK COBURN", p1Start: 0, p2: "Freddie Russell", p2Start: 0 },
        { p1: "Freddie Russell", p1Start: 0, p2: "PAUL RODD", p2Start: 0 },
        { p1: "CHRIS ISAACS", p1Start: 0, p2: "Freddie Russell", p2Start: 0 },
        { p1: "GUY SMITH", p1Start: 0, p2: "Freddie Russell", p2Start: 0 },
        { p1: "Freddie Russell", p1Start: 0, p2: "ALEX BURNETT", p2Start: 0 },
        { p1: "DAVID ODWELL", p1Start: 0, p2: "Freddie Russell", p2Start: 0 },
        { p1: "Freddie Russell", p1Start: 0, p2: "STUART SMITH", p2Start: 0 },
        { p1: "AARON WATERER", p1Start: 0, p2: "Freddie Russell", p2Start: 0 },
        { p1: "Freddie Russell", p1Start: 0, p2: "William Sturdy", p2Start: 0 }     
    ],

    populateDropdown: function(dropdownId) {
        const dropdown = document.getElementById(dropdownId);
        if (!dropdown) return;
        dropdown.innerHTML = '<option value="">-- Choose Match --</option>';
        this.matches.forEach((match, index) => {
            const option = document.createElement('option');
            option.value = index;
            option.textContent = `${match.p1} vs ${match.p2}`;
            dropdown.appendChild(option);
        });
    }
};
