// generateReport.js - Reporting Utility for Champions League

const ReportGenerator = {
    // This connects to your ChampionsLeague logic
    generateLeagueReport: function() {
        const now = new Date();
        const dateStr = now.toLocaleDateString('en-GB') + ", " + now.toLocaleTimeString('en-GB', { hour12: false });
        const durationText = typeof getDuration === 'function' ? getDuration() : "00:00:00";
        
        // 1. HEADER SECTION
        const startP1 = gameState.p1ScoreStart || 0;
        const startP2 = gameState.p2ScoreStart || 0;
        const reportTitle = (startP1 !== 0 || startP2 !== 0) ? 'Bar 8 Champions League Active' : 'Bar 8 Champions League';
        const centeredTitle = reportTitle.length >= 49
            ? reportTitle
            : reportTitle.padStart(Math.floor((49 + reportTitle.length) / 2)).padEnd(49);
        let report = `╔═════════════════════════════════════════════════════╗\n`;
        report += `║ ${centeredTitle} ║\n`;
        report += `╚═════════════════════════════════════════════════════╝\n\n`;
        
        const totalGames = Math.max(1, gameState.p1Matches + gameState.p2Matches);
        const reportType = gameState.raceTo === 11 ? `STANDARD RACE TO ${gameState.raceTo}` : `RACE TO ${gameState.raceTo} * ${totalGames}`;
        
        report += `DATE:      ${dateStr}\n`;
        report += `MATCH ID:  ${gameState.matchID || 'SESSION-ACTIVE'}\n`; 
        report += `TYPE:      ${reportType}\n`;
        report += `STATUS:    FINISHED ✅\n`;
        report += `DURATION:  ${durationText}\n`;
        report += `------------------------------------------------------\n`;
        report += `SCORE:     ${gameState.p1Name} (${gameState.p1Score}) - ${gameState.p2Name} (${gameState.p2Score})\n`;
        report += `------------------------------------------------------\n`;

        // 2. PLAYER STATISTICS SECTION
        let p1F = 0, p1A = 0, p2F = 0, p2A = 0;
        matchHistory.forEach(f => {
            if (f.winner === gameState.p1Name) { p1F++; p2A++; }
            else { p2F++; p1A++; }
        });

        report += `PLAYER STATISTICS:\n`;
        report += `${gameState.p1Name.padEnd(15)} | DISHES: ${gameState.p1Dishes} | REV: ${gameState.p1RevDishes}\n`;
        report += `${gameState.p1Name.padEnd(15)} | FRAME-F: ${p1F} | FRAME-A: ${p1A}\n`;
        report += `${gameState.p2Name.padEnd(15)} | DISHES: ${gameState.p2Dishes} | REV: ${gameState.p2RevDishes}\n`;
        report += `${gameState.p2Name.padEnd(15)} | FRAME-F: ${p2F} | FRAME-A: ${p2A}\n`;
        report += `------------------------------------------------------\n\n`;

        // 3. MATCH PROGRESS LOG (The "Result" Logic)
        report += `MATCH PROGRESS LOG:\n`;
        
        // Use handicaps from champions.js if they were loaded into gameState
        let currentP1 = gameState.p1ScoreStart || 0; 
        let currentP2 = gameState.p2ScoreStart || 0;

        report += `[✔] FRAME 0     | STARTING SCORES              | SCORE: ${gameState.p1Name} (${currentP1}) - ${gameState.p2Name} (${currentP2})\n`;

        matchHistory.forEach((item, index) => {
            if (item.winner === gameState.p1Name) currentP1++;
            else currentP2++;

            const frameTitle = `FRAME ${index + 1}`.padEnd(12);
            const winnerName = `WINNER: ${item.winner}`.padEnd(25);
            const moveType = item.type === 'normal' ? 'NORMAL'.padEnd(15) : item.type.toUpperCase().padEnd(15);
            
            // Score formatting with padding for negative numbers/alignment
            const s1 = (currentP1 >= 0 ? ` ${currentP1}` : `${currentP1}`).padStart(3);
            const s2 = (currentP2 >= 0 ? ` ${currentP2}` : `${currentP2}`).padStart(3);

            report += `[✔] ${frameTitle} | ${winnerName} | ${moveType} | SCORE: ${gameState.p1Name} (${s1}) - ${gameState.p2Name} (${s2})\n`;
        });

        report += `\n______________________________________________________\n`;
        report += `           GENERATED BY Freddie Russell          `;
        
        return report;
    }
};